//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paperless {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaperlessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaperlessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paperless.PaperlessResources", typeof(PaperlessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .paperless-attachment {  max-width: 90%;  height: auto;}
        ///embed.paperless-attachment { min-width:90%; height: 720px;}
        ///.paperless-attachment-file {
        ///   height: 70px;
        ///   width: 250px;
        ///   border-color: lightblue;
        ///   color: blue;
        ///   text-weight: light;
        ///   border-width: 1px;
        ///   background: url(&apos;images/&apos;+attr(&apos;data-ext&apos;)+&apos;-icon-48x48.png&apos;);
        ///   background-repeat: no-repeat;
        ///   background-position: left;
        ///   border-style: solid;
        ///   padding1: 5 5 5 50;
        ///   text-align: center;
        ///   text-overflow: ellipsis;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string paperless_css {
            get {
                return ResourceManager.GetString("paperless_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.onload = function(e) {
        ///	var list = document.getElementsByClassName(&apos;paperless-attachment-file&apos;);
        ///
        ///for (var i = 0; i &lt; list.length; i++) {
        ///  var src = list[i].getAttribute(&apos;data-ext&apos;);
        ///  list[i].style.backgroundImage=&quot;url(&apos;images/&quot; + src.substring(1) + &quot;-icon-48x48.png&apos;)&quot;;
        ///}
        ///}.
        /// </summary>
        internal static string paperless_js {
            get {
                return ResourceManager.GetString("paperless_js", resourceCulture);
            }
        }
    }
}
